In [13]:
import numpy as np

In [14]:
matrix = np.array([[1, 2, 3],
                   [2, 3, 1],
                   [3, 1, 2]])
print(matrix)

[[1 2 3]
 [2 3 1]
 [3 1 2]]


In [15]:
while matrix.shape[0] < 192:
    lr = np.fliplr(matrix)                         #разворачиваем матрицу слева направо
    matrix = np.concatenate((matrix, lr), axis=1)  #присоединяем к исходной справа
    ud = np.flipud(matrix)                         #разворачиваем матрицу сверху вниз
    matrix = np.concatenate((matrix, ud), axis=0)  #присоединяем к исходной снизу

In [18]:
print(matrix)
print(matrix.shape[0])

[[1 2 3 ... 3 2 1]
 [2 3 1 ... 1 3 2]
 [3 1 2 ... 2 1 3]
 ...
 [3 1 2 ... 2 1 3]
 [2 3 1 ... 1 3 2]
 [1 2 3 ... 3 2 1]]
192
