In [105]:
import numpy as np

np.random.seed(5041)

print("1. Сгенерировать матрицу размером 4 × 4, заполненную целыми числами.")
matrix = np.random.randint(1, 20, size=(4,4))
print(matrix)

1. Сгенерировать матрицу размером 4 × 4, заполненную целыми числами.
[[17 16 18  5]
 [12 11  7  7]
 [16 19 16  3]
 [ 4 16  3 16]]


In [106]:
print("2. Вывести на экран элемент с индексами [3, 2].")
print(matrix[3][2])

2. Вывести на экран элемент с индексами [3, 2].
3


In [107]:
print("3.  Вывести на экран вторую строку матрицы.")
print(matrix[1])

3.  Вывести на экран вторую строку матрицы.
[12 11  7  7]


In [108]:
print("4. Вывести на экран каждый второй элемент первой строки матрицы.")
print(matrix[0][1::2])

4. Вывести на экран каждый второй элемент первой строки матрицы.
[16  5]


In [109]:
print("5. Изменить форму матрицы с 4 × 4 на 8 × 2.")
new_reshape_matrix = matrix.reshape(8, 2)
print(new_reshape_matrix)

5. Изменить форму матрицы с 4 × 4 на 8 × 2.
[[17 16]
 [18  5]
 [12 11]
 [ 7  7]
 [16 19]
 [16  3]
 [ 4 16]
 [ 3 16]]


In [110]:
print("6. Вычесть из каждого элемента матрицы заданное число.")
k = 6
new_k_matrix = matrix - k
print(new_k_matrix)

6. Вычесть из каждого элемента матрицы заданное число.
[[11 10 12 -1]
 [ 6  5  1  1]
 [10 13 10 -3]
 [-2 10 -3 10]]


In [111]:
print("7. Найти минимум на главной диагонали матрицы.")
print(np.min(np.diag(matrix)))

7. Найти минимум на главной диагонали матрицы.
11


In [112]:
print("8. Найти максимальный элемент в последнем столбце.")
print(np.max(matrix[::, -1]))

8. Найти максимальный элемент в последнем столбце.
16


In [113]:
print("9. Дан одномерный массив. Определить процент положительных и отрицательных чисел.")
array = np.random.randint(-10, 10, 10)
n = len(array)
print(array)
negative_percentage = np.sum(array < 0) / n * 100
positive_percantage = np.sum(array > 0) / n * 100
print("Процент положительных чисел: ", positive_percantage)
print("Процент отрицательных чисел: ", negative_percentage)

9. Дан одномерный массив. Определить процент положительных и отрицательных чисел.
[-8 -7 -4 -5 -6  3 -8  7  3  3]
Процент положительных чисел:  40.0
Процент отрицательных чисел:  60.0


In [114]:
print("10. В заданной матрице подсчитать среднее геометрическое двузначных чисел, расположенных в четных столбцах матрицы.")

new_matrix = np.random.randint(1, 20, size=(6,6))
print(new_matrix)

print("Элементы четных столбцов: ")
select = new_matrix[:, 1::2].flatten()
print(select)

print("Только двузначные: ")
only_two_digits = select[(select >= 10) & (select < 100)]     #маска
print(only_two_digits)

print("Среднее геометрическое: ")
geom_mean = np.prod(only_two_digits) ** (1/len(only_two_digits))
print(geom_mean)

10. В заданной матрице подсчитать среднее геометрическое двузначных чисел, расположенных в четных столбцах матрицы.
[[18  6 17  7 16 18]
 [10  3 10 19 13  2]
 [13 17  3 14 16  5]
 [ 9  2 10  5  8 12]
 [ 3  3  5  2  9  2]
 [18  6  4 12  9 10]]
Элементы четных столбцов: 
[ 6  7 18  3 19  2 17 14  5  2  5 12  3  2  2  6 12 10]
Только двузначные: 
[18 19 17 14 12 12 10]
Среднее геометрическое: 
14.21377266405881
