In [8]:
import numpy as np

print("11. Выполнить обработку элементов квадратной матрицы 𝐴, имеющей 𝑛 строк и 𝑛 столбцов. Заменить значения элементов главной диагонали на среднее арифметическое элементов соответствующих строки и столбца.")

11. Выполнить обработку элементов квадратной матрицы 𝐴, имеющей 𝑛 строк и 𝑛 столбцов. Заменить значения элементов главной диагонали на среднее арифметическое элементов соответствующих строки и столбца.


In [9]:
np.random.seed(555)
n = 6
matrix = np.random.randint(1, 10, size=(n, n)).astype(float)
print(matrix)

[[2. 5. 7. 7. 1. 6.]
 [1. 5. 7. 7. 6. 6.]
 [1. 5. 2. 5. 4. 4.]
 [4. 4. 5. 8. 9. 4.]
 [2. 5. 2. 2. 9. 5.]
 [1. 2. 5. 5. 1. 1.]]


In [10]:
row_means = np.mean(matrix, axis=1) #вычисляем среднее по всем строкам
col_means = np.mean(matrix, axis=0) #вычисляем среднее по всем столбцам

np.fill_diagonal(matrix, (row_means + col_means) / 2)
print(matrix)

[[3.25       5.         7.         7.         1.         6.        ]
 [1.         4.83333333 7.         7.         6.         6.        ]
 [1.         5.         4.08333333 5.         4.         4.        ]
 [4.         4.         5.         5.66666667 9.         4.        ]
 [2.         5.         2.         2.         4.58333333 5.        ]
 [1.         2.         5.         5.         1.         3.41666667]]
