In [5]:
import numpy as np
np.random.seed(6845)

print("11. Дан вектор 𝑥 и матрица 𝐴. Умножить все четные строки матрицы 𝐴 на вектор 𝑥. Результат записать в новую матрицу и умножить ее на сумму элементов вектора 𝑥.")

n = 6
matrixA = np.random.randint(1, 10, size=(n, n)).astype(float)
print(matrixA)

vectorX = np.random.randint(1, 10, size=(n, 1)).astype(float)
print(vectorX)

11. Дан вектор 𝑥 и матрица 𝐴. Умножить все четные строки матрицы 𝐴 на вектор 𝑥. Результат записать в новую матрицу и умножить ее на сумму элементов вектора 𝑥.
[[9. 6. 5. 3. 5. 3.]
 [3. 5. 5. 1. 4. 4.]
 [6. 8. 7. 9. 1. 8.]
 [3. 8. 1. 6. 8. 9.]
 [3. 8. 4. 5. 1. 9.]
 [7. 1. 4. 9. 5. 4.]]
[[8.]
 [3.]
 [4.]
 [5.]
 [1.]
 [2.]]


In [13]:
even_matrixA = matrixA[1::2]
print(even_matrixA)

[[3. 5. 5. 1. 4. 4.]
 [3. 8. 1. 6. 8. 9.]
 [7. 1. 4. 9. 5. 4.]]


In [10]:
res_matrix = np.dot(even_matrixA, vectorX) * np.sum(vectorX) #формируем матрицу из четных строк исходной, 
                                                             #умножаем матрично на х (эквивалентно условию задачи)
                                                             #умножаем каждый элемент на сумму
print(res_matrix)

[[1748.]
 [2484.]
 [3059.]]
